name=STS3032
version=0.0.1
author=Julien Nguyen
maintainer=Julien Nguyen
sentence=This library allows to control the Feetech STS3032 servo motor with STM32 Nucleo boards.
paragraph=The library provides functions to control the Feetech STS3032 servo motor, including setting the position, speed, and torque. It is designed for use with STM32 Nucleo boards.
category=Other
url=https://www.feetechrc.com/STS3032.html
architectures=stm32
